// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzDaNLBPa1XpAflbxmYxSnakCir9nSg1U',
    appId: '1:773972437619:web:3ab0d26878cec6672ad806',
    messagingSenderId: '773972437619',
    projectId: 'prueba-bd-81b78',
    authDomain: 'prueba-bd-81b78.firebaseapp.com',
    storageBucket: 'prueba-bd-81b78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeoGOxNbe-KjQGxbiBRjD2llKXDPNE5eQ',
    appId: '1:773972437619:android:b229dda41cced83b2ad806',
    messagingSenderId: '773972437619',
    projectId: 'prueba-bd-81b78',
    storageBucket: 'prueba-bd-81b78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeoGOxNbe-KjQGxbiBRjD2llKXDPNE5eQ',
    appId: '1:773972437619:ios:600722619ef0456c2ad806',
    messagingSenderId: '773972437619',
    projectId: 'prueba-bd-81b78',
    storageBucket: 'prueba-bd-81b78.appspot.com',
    androidClientId: '773972437619-eok1n71v4t1t97hck3elhucrh0hbl8qu.apps.googleusercontent.com',
    iosClientId: '773972437619-vnsch78tmunf1kf68jullsgq1m6mvi9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcoclean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeoGOxNbe-KjQGxbiBRjD2llKXDPNE5eQ',
    appId: '1:773972437619:ios:35f15a36bf305fb82ad806',
    messagingSenderId: '773972437619',
    projectId: 'prueba-bd-81b78',
    storageBucket: 'prueba-bd-81b78.appspot.com',
    androidClientId: '773972437619-eok1n71v4t1t97hck3elhucrh0hbl8qu.apps.googleusercontent.com',
    iosClientId: '773972437619-ajuhhv87k51fgjggkpndvlmelnttjvc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcoclean.RunnerTests',
  );
}
